package projectoop;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;




public class CarRegistrationForm extends javax.swing.JFrame {

    
    private Car car;
    private Customer customer;
    private Bank bank;
    private int count;
    private String model;
    private Double price;
    
    DBController dbCtrl;
    
    public CarRegistrationForm(int count) {
        this.count = count;
        initComponents();
        createObject();
  
        dbCtrl = new DBController();
        dbCtrl.setConnect();
        
        submtBtn.setEnabled(false);
        ResBtn.setEnabled(false);
        
        
    }

    
    public void createObject(){
        car = new Car();
        customer = new Customer();
        bank = new Bank();
    }
    
    private void clearInputForm1() {
    
    typeTxtFld.setText("");
    transTxtFld.setText("");
   
}
    
    private void clearInputForm() {
    modelTxtFld.setText("");
    bankTxtFld.setText("");
    loanTxtFld.setText("");
    downPayTxtFld.setText("");
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        titleLbl = new javax.swing.JLabel();
        typeLbl = new javax.swing.JLabel();
        transLbl = new javax.swing.JLabel();
        modelLbl = new javax.swing.JLabel();
        loanLbl = new javax.swing.JLabel();
        downPayLbl = new javax.swing.JLabel();
        bankLbl = new javax.swing.JLabel();
        submtBtn = new javax.swing.JButton();
        ResBtn = new javax.swing.JButton();
        sendBtn = new javax.swing.JButton();
        option1Lbl = new javax.swing.JLabel();
        option2Lbl = new javax.swing.JLabel();
        option3Lbl = new javax.swing.JLabel();
        loanTxtFld = new javax.swing.JTextField();
        downPayTxtFld = new javax.swing.JTextField();
        modelTxtFld = new javax.swing.JTextField();
        typeTxtFld = new javax.swing.JTextField();
        transTxtFld = new javax.swing.JTextField();
        sedanLbl = new javax.swing.JLabel();
        supCarLbl = new javax.swing.JLabel();
        mpvLbl = new javax.swing.JLabel();
        manualLbl = new javax.swing.JLabel();
        autoLbl = new javax.swing.JLabel();
        bankTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titleLbl.setText("Register Your Car");

        typeLbl.setText("Choose your car type:");

        transLbl.setText("Choose transmission: ");

        modelLbl.setText("Choose you model:");

        loanLbl.setText("Loan Duration (years);");

        downPayLbl.setText("Down payment (percentage):");

        bankLbl.setText("Bank:");

        submtBtn.setText("SUBMIT");
        submtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submtBtnActionPerformed(evt);
            }
        });

        ResBtn.setText("RESULT");
        ResBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResBtnActionPerformed(evt);
            }
        });

        sendBtn.setText("SEND");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });

        option1Lbl.setText("Option1");

        option2Lbl.setText("Option2");

        option3Lbl.setText("Option2");

        modelTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTxtFldActionPerformed(evt);
            }
        });

        transTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transTxtFldActionPerformed(evt);
            }
        });

        sedanLbl.setText("0 - Sedan");

        supCarLbl.setText("1 - Super Car");

        mpvLbl.setText("2 - MPV");

        manualLbl.setText("0 - Manual");

        autoLbl.setText("1 - Auto");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(titleLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(typeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(transLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sendBtn)
                        .addComponent(transTxtFld)
                        .addComponent(typeTxtFld, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(sedanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supCarLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpvLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manualLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(autoLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loanLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(downPayLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loanTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(downPayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ResBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(modelLbl)
                                        .addGap(122, 122, 122))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(option1Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(option2Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(8, 8, 8))
                                            .addComponent(option3Lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bankLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bankTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 127, Short.MAX_VALUE)))
                        .addGap(165, 165, 165))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modelTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submtBtn)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(bankLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bankTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(typeLbl)
                                    .addComponent(modelLbl))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sedanLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(supCarLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mpvLbl))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(option1Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(option2Lbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(option3Lbl)))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(loanLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(loanTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(downPayLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(downPayTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(typeTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(transLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(manualLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(autoLbl)
                                .addGap(16, 16, 16)
                                .addComponent(transTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(submtBtn)
                        .addGap(117, 117, 117)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ResBtn))
                    .addComponent(sendBtn))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
            
        car.setType(typeTxtFld.getText());
        car.setTransmission(transTxtFld.getText());
        
        
        if(car.getType().equals("0"))
        {
            if(car.getTransmission().equals("Manual") || car.getTransmission().equals("Auto"))
            {
                 option1Lbl.setText("0 -> 2023 Toyota Vios 1.5E AT");
                 option2Lbl.setText("1 -> 2019 Proton Persona Executive 1.6");
                 option3Lbl.setText("2 -> Honda CR-V 2.0");
            }
            
        }
        else if(car.getType().equals("1"))
        {
             if(car.getTransmission().equals("Manual") || car.getTransmission().equals("Auto"))
            {
               option1Lbl.setText("0 -> 2022 Perodua Alza 1.5 X");
               option2Lbl.setText("1 -> 2019 Toyota Avanza 1.5E");
               option3Lbl.setText("2 -> 2023 Toyota Vellfire 2.5"); 
            }
        
        }
        else if(car.getType().equals("2"))
        {
             if(car.getTransmission().equals("Manual") || car.getTransmission().equals("Auto"))
            {
               option1Lbl.setText("0 -> Aston Martin Vanquish");
               option2Lbl.setText("1 -> 2021 Porsche Taycan RWD ");
               option3Lbl.setText("2 -> 2022 Ferrari 296 GTB V6"); 
            }
            
        }
             
        if(car.getType() != null){
        
            submtBtn.setEnabled(true);
            ResBtn.setEnabled(true);
            sendBtn.setEnabled(false);
        
        }
       
    }//GEN-LAST:event_sendBtnActionPerformed

    private void transTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transTxtFldActionPerformed

    private void submtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submtBtnActionPerformed
        
        
        
       


        if(typeTxtFld.getText().equals("0"))
        {   
            car = new Sedan();
            car.setType("Sedan");

            if(modelTxtFld.getText().equalsIgnoreCase("0")) ((Sedan)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("1")) ((Sedan)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("2")) ((Sedan)car).setModel((modelTxtFld.getText()));
            else JOptionPane.showMessageDialog(null, "Wrong input, please try again");
            
            if(transTxtFld.getText().equalsIgnoreCase("0")) ((Sedan)car).setTransmission((transTxtFld.getText()));
            else if(transTxtFld.getText().equalsIgnoreCase("1")) ((Sedan)car).setTransmission((transTxtFld.getText()));

            price = ((Sedan)car).calculatePrice();
            model = ((Sedan)car).getModel(Integer.parseInt(modelTxtFld.getText()));
        }
        else if(typeTxtFld.getText().equals("1"))
        {
            car = new SuperCar();
            car.setType("SuperCar");

            if(modelTxtFld.getText().equalsIgnoreCase("0")) ((SuperCar)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("1")) ((SuperCar)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("2")) ((SuperCar)car).setModel((modelTxtFld.getText()));
            else JOptionPane.showMessageDialog(null, "Wrong input, please try again");
            
            if(transTxtFld.getText().equalsIgnoreCase("0")) ((SuperCar)car).setTransmission((transTxtFld.getText()));
            else if(transTxtFld.getText().equalsIgnoreCase("1")) ((SuperCar)car).setTransmission((transTxtFld.getText()));

            price = ((Sedan)car).calculatePrice();
            model = ((SuperCar)car).getModel(Integer.parseInt(modelTxtFld.getText()));
        }
        else if(typeTxtFld.getText().equals("2"))
        {
            car = new MPV();
            car.setType("MPV");

            if(modelTxtFld.getText().equalsIgnoreCase("0")) ((MPV)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("1")) ((MPV)car).setModel((modelTxtFld.getText()));
            else if(modelTxtFld.getText().equalsIgnoreCase("2")) ((MPV)car).setModel((modelTxtFld.getText()));
            else JOptionPane.showMessageDialog(null, "Wrong input, please try again");
            
            if(transTxtFld.getText().equalsIgnoreCase("0")) ((MPV)car).setTransmission((transTxtFld.getText()));
            else if(transTxtFld.getText().equalsIgnoreCase("1")) ((MPV)car).setTransmission((transTxtFld.getText()));
            
            price = ((Sedan)car).calculatePrice();
            model = ((MPV)car).getModel(Integer.parseInt(modelTxtFld.getText()));
            
        }

        String insertQuery = "INSERT INTO car VALUES (?,?,?,?,?,?,?,?)";
        
        try{
            dbCtrl.pstmt = dbCtrl.myConn.prepareStatement(insertQuery);
            dbCtrl.pstmt.setInt(1, 1);
            dbCtrl.pstmt.setString(2, car.getType());
            dbCtrl.pstmt.setString(3, car.getTransmission());
            dbCtrl.pstmt.setString(4, model);
            dbCtrl.pstmt.setDouble(5, price);
            dbCtrl.pstmt.setDouble(6, Double.parseDouble(loanTxtFld.getText()));
            dbCtrl.pstmt.setDouble(7,  Double.parseDouble(downPayTxtFld.getText()));
            dbCtrl.pstmt.setString(8,bankTxtFld.getText());

            dbCtrl.pstmt.executeUpdate();
            

            JOptionPane.showMessageDialog(null, "Your car info is successfully submitted");

            clearInputForm();
            

            }
        
        catch(NumberFormatException e){
            System.out.println("Error: " + e.getMessage());
//            speedTxtFld.setText("");
//            speedTxtFld.requestFocus();
        
        }
        
        catch(SQLException e){
            System.out.println("Error: " + e.getMessage());
        }
        
        catch(ClassCastException c)
        {
            System.out.println("Error: " + c.getMessage());
        }
        
         
        if(car.getType() != null){
        
            submtBtn.setEnabled(false);
            ResBtn.setEnabled(true);
            sendBtn.setEnabled(false);

        }
        
        
        //        customer.setLoanDuration(Integer.parseInt(loanTxtFld.getText()));
//        customer.setDownPayment(Integer.parseInt(downPayTxtFld.getText()));
//        bank.setBankName(bankTxtFld.getText());
//        customer.setPayment(Integer.parseInt(payTxtFld.getText()));
        

     
    }//GEN-LAST:event_submtBtnActionPerformed

    private void modelTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelTxtFldActionPerformed

    private void ResBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResBtnActionPerformed
       
//        try 
//        {
//        String updateQuery = "UPDATE car SET type=?, transmission=?, model=? WHERE ID=?";
//            
//                dbCtrl.pstmt = dbCtrl.myConn.prepareStatement(updateQuery);
//                dbCtrl.pstmt.setString(1, car.getType());
//                dbCtrl.pstmt.setString(2, car.getTransmission());
//                dbCtrl.pstmt.setString(3, model);
//                dbCtrl.pstmt.setInt(4, 1);
//
//                dbCtrl.pstmt.executeUpdate();
//        }
//        
//        catch(SQLException e)
//        {
//            System.out.println("Error: " + e.getMessage());
//        }
        
        clearInputForm();
        CarDisplayForm display = new CarDisplayForm(customer, car);
        display.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_ResBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CarRegistrationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResBtn;
    private javax.swing.JLabel autoLbl;
    private javax.swing.JLabel bankLbl;
    private javax.swing.JTextField bankTxtFld;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JLabel downPayLbl;
    private javax.swing.JTextField downPayTxtFld;
    private javax.swing.JLabel loanLbl;
    private javax.swing.JTextField loanTxtFld;
    private javax.swing.JLabel manualLbl;
    private javax.swing.JLabel modelLbl;
    private javax.swing.JTextField modelTxtFld;
    private javax.swing.JLabel mpvLbl;
    private javax.swing.JLabel option1Lbl;
    private javax.swing.JLabel option2Lbl;
    private javax.swing.JLabel option3Lbl;
    private javax.swing.JLabel sedanLbl;
    private javax.swing.JButton sendBtn;
    private javax.swing.JButton submtBtn;
    private javax.swing.JLabel supCarLbl;
    private javax.swing.JLabel titleLbl;
    private javax.swing.JLabel transLbl;
    private javax.swing.JTextField transTxtFld;
    private javax.swing.JLabel typeLbl;
    private javax.swing.JTextField typeTxtFld;
    // End of variables declaration//GEN-END:variables
}
